/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SM.AVC.IU;

import static com.sun.jmx.trace.Trace.isSelected;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author ali_a
 */
public class Celda extends javax.swing.JPanel implements ListCellRenderer<Color>{

    /**
     * Creates new form NewJPanel
     */
    public Celda() {
        initComponents();
    }
    //este atributo devuelve el color
    private Color colorCelda;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new javax.swing.JButton();

        boton.setPreferredSize(new java.awt.Dimension(25, 25));
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        add(boton);
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActionPerformed

    @Override
    public Component getListCellRendererComponent(JList<? extends Color> jlist, Color e, int i, boolean bln, boolean bln1) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        boton.setBackground(e);
        // check if this cell represents the current DnD drop location
         Color background;
         colorCelda = e;
         boton.setBackground(e);
         JList.DropLocation dropLocation = jlist.getDropLocation();
         if (dropLocation != null
                 && !dropLocation.isInsert()
                 && dropLocation.getIndex() == i) {

             background = Color.gray;
             

         // check if this cell is selected
         } else if (bln) {
             background = Color.gray;

         // unselected, and not the DnD drop location
         } else {
             background = Color.lightGray;
         }
         this.setBackground(background);
        
         return this;
    }
    
    public Color getColorCelda(){
        return colorCelda;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    // End of variables declaration//GEN-END:variables
}
