/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;
import java.io.File;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;
/**
 *
 * @author ali_a
 */
public class VentanaReproduccion extends javax.swing.JInternalFrame {

     SMPlayer player = null;
    /**
     * Creates new form VentanaSonido
     */
    public VentanaReproduccion(File f) {
        initComponents();
        player = new SMClipPlayer(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPlay = new javax.swing.JToggleButton();
        botonParar = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play24x24.png"))); // NOI18N
        botonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(botonPlay);

        botonParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pausa24x24.png"))); // NOI18N
        botonParar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PlayPressed_48x48.png"))); // NOI18N
        botonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPararActionPerformed(evt);
            }
        });
        getContentPane().add(botonParar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayActionPerformed
        // TODO add your handling code here:
        if(player != null)
            player.play();
    }//GEN-LAST:event_botonPlayActionPerformed

    private void botonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPararActionPerformed
        // TODO add your handling code here:
         if(player != null)
            player.stop();
    }//GEN-LAST:event_botonPararActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonParar;
    private javax.swing.JToggleButton botonPlay;
    // End of variables declaration//GEN-END:variables
}
