/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;
import java.io.File;
import sm.sound.SMSoundPlayerRecorder;
/**
 *
 * @author ali_a
 */
public class VentanaGrabacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaGrabacion
     */
    
    //variable destinada a almacenar el sonido grabado
    SMSoundPlayerRecorder grabacion;
    public VentanaGrabacion(File f) {
        initComponents();
        grabacion = new SMSoundPlayerRecorder(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRecord = new javax.swing.JToggleButton();
        botonStop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        botonRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/record24x24.png"))); // NOI18N
        botonRecord.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecordDisabled_48x48.png"))); // NOI18N
        botonRecord.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RecordPressed_48x48.png"))); // NOI18N
        botonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecordActionPerformed(evt);
            }
        });
        getContentPane().add(botonRecord);

        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pausa24x24.png"))); // NOI18N
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });
        getContentPane().add(botonStop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecordActionPerformed
        // TODO add your handling code here:
        grabacion.record();
    }//GEN-LAST:event_botonRecordActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        // TODO add your handling code here:
    
        grabacion.stop();
    }//GEN-LAST:event_botonStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonRecord;
    private javax.swing.JToggleButton botonStop;
    // End of variables declaration//GEN-END:variables
}
