/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.JPanel;
//import static sun.audio.AudioPlayer.player;



/**
 *
 * @author ali_a
 */
public class VentanaCamara extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCamara
     */
    private Webcam camara = null;
    
    public VentanaCamara() {
        initComponents();
        List<Webcam> xc = Webcam.getWebcams();
        for(Webcam c : xc)
            System.out.print("camaras" + c);
        camara = Webcam.getDefault();
        Dimension resoluciones[] = camara.getViewSizes();
        Dimension maxRes = resoluciones[resoluciones.length-1];
        camara.setViewSize(maxRes);
        if (camara != null) {
            JPanel areaVisual = new WebcamPanel(camara);
            if (areaVisual!= null) {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
        
        
    }
    
    public static VentanaCamara getInstance(){
        VentanaCamara v = new VentanaCamara();
        return (v.camara!=null?v:null);
    }

    public BufferedImage captura(){
        return camara.getImage();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
