/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

import SM.AVC.IU.Herramientas;
//import SM.AVC.IU.Lienzo;
import SM.AVC.IU.Lienzo2DImagen;
import SM.AVC.IU.LienzoProyecto;
import java.awt.Color;

/**
 *
 * @author Ana Alcia Vílchez Ceballos,  ETSIIT (UGR)
 */

public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    
    VentanaPrincipal parent = null;
    
    public VentanaInterna() {
        initComponents();
    }
    
    public VentanaInterna(VentanaPrincipal v){
        initComponents();
        parent = v;
        repaint();

    }
    //este metodo se utilizara cada vez que clickeemos la ventana
    private VentanaPrincipal getP(){
        return parent;
    }
    
    //get del lienzo
    public LienzoProyecto getLienzo() {
        return lienzo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new SM.AVC.IU.LienzoProyecto();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lienzoMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        parent = getP();
    }//GEN-LAST:event_formMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if(lienzo.getTipoGradiente() == "relleno")
            parent.getRellenar().setSelected(true);
        else if(lienzo.getTipoGradiente() == "gradienteH")
            parent.getDegradadoHorizontal().setSelected(true);
        else if(lienzo.getTipoGradiente() == "gradienteV")
            parent.getDegradadoVertical().setSelected(true);
        
        parent.getBotonEditar().setSelected(lienzo.isEditar());
        parent.getGrosor().setValue(lienzo.getGrosor());
        //para la transparencia
        if(lienzo.getNivelTransparencia() == 0)
            parent.getNivelTransparencia().setSelectedIndex(0);   
        else if(lienzo.getNivelTransparencia() == 0.1)      
            parent.getNivelTransparencia().setSelectedIndex(1);    
        else if(lienzo.getNivelTransparencia() == 0.2)      
            parent.getNivelTransparencia().setSelectedIndex(2);    
        else if(lienzo.getNivelTransparencia() == 0.3)      
            parent.getNivelTransparencia().setSelectedIndex(3);    
        else if(lienzo.getNivelTransparencia() == 0.4)      
            parent.getNivelTransparencia().setSelectedIndex(4);    
        else if(lienzo.getNivelTransparencia() == 0.5)      
            parent.getNivelTransparencia().setSelectedIndex(5);    
        else if(lienzo.getNivelTransparencia() == 0.6)      
            parent.getNivelTransparencia().setSelectedIndex(6);    
        else if(lienzo.getNivelTransparencia() == 0.7)      
            parent.getNivelTransparencia().setSelectedIndex(7);    
        else if(lienzo.getNivelTransparencia() == 0.8)      
            parent.getNivelTransparencia().setSelectedIndex(8);    
        else if(lienzo.getNivelTransparencia() == 0.9)      
            parent.getNivelTransparencia().setSelectedIndex(9);    
        else if(lienzo.getNivelTransparencia() == 1)      
            parent.getNivelTransparencia().setSelectedIndex(10);    
                                                                           
        parent.getAlisar().setSelected(lienzo.isAlisado());
        
        //para la herramienta
        if(lienzo.getEnUso() == Herramientas.LAPIZ){
            parent.getLapiz().setSelected(true);
            parent.getBarraEstado().setText("Punto");
        }
        else if(lienzo.getEnUso() == Herramientas.RECTA){
            parent.getRecta().setSelected(true);
            parent.getBarraEstado().setText("Linea");
        }
        else if(lienzo.getEnUso() == Herramientas.RECTANGULO){
            parent.getRectangulo().setSelected(true);
            parent.getBarraEstado().setText("Rectangulo");
        }
        else if(lienzo.getEnUso() == Herramientas.OVALO){
            parent.getCirculo().setSelected(true);
            parent.getBarraEstado().setText("Ovalo");
        }
        else if(lienzo.getEnUso() == Herramientas.CURVA){
            parent.getBotonCurva().setSelected(true);
            parent.getBarraEstado().setText("Curva");
        }
        else if(lienzo.getEnUso() == Herramientas.TEXTO){
            parent.getBotonTexto().setSelected(true);
            parent.getBarraEstado().setText("Texto");
        }
        //para los colores DEL BORDE
        /*
        if(lienzo.getColorAsignado() == Color.BLACK)
            parent.getBoxColores().setSelectedItem(Color.BLACK);
        
        else if(lienzo.getColorAsignado() == Color.BLUE)
            parent.getBoxColores().setSelectedItem(Color.BLUE);
        
        else if(lienzo.getColorAsignado() == Color.GREEN)
            parent.getBoxColores().setSelectedItem(Color.GREEN);
        
        else if(lienzo.getColorAsignado() == Color.RED)
            parent.getBoxColores().setSelectedItem(Color.RED);
        
        else if(lienzo.getColorAsignado() == Color.WHITE)
            parent.getBoxColores().setSelectedItem(Color.WHITE);   
        
        else if(lienzo.getColorAsignado() == Color.YELLOW)
            parent.getBoxColores().setSelectedItem(Color.YELLOW);
        
        else if(lienzo.getColorAsignado() == Color.PINK)
            parent.getBoxColores().setSelectedItem(Color.PINK);
        
        else if(lienzo.getColorAsignado() == Color.ORANGE)
            parent.getBoxColores().setSelectedItem(Color.ORANGE);
        
        //Para los colores del relleno
        
         if(lienzo.getColorRelleno() == Color.BLACK)
            parent.getBoxColores2().setSelectedItem(Color.BLACK);
        
        else if(lienzo.getColorRelleno() == Color.BLUE)
            parent.getBoxColores2().setSelectedItem(Color.BLUE);
        
        else if(lienzo.getColorRelleno() == Color.GREEN)
            parent.getBoxColores2().setSelectedItem(Color.GREEN);
        
        else if(lienzo.getColorRelleno() == Color.RED)
            parent.getBoxColores2().setSelectedItem(Color.RED);
        
        else if(lienzo.getColorRelleno() == Color.WHITE)
            parent.getBoxColores2().setSelectedItem(Color.WHITE);   
        
        else if(lienzo.getColorRelleno() == Color.YELLOW)
            parent.getBoxColores2().setSelectedItem(Color.YELLOW);
        
        else if(lienzo.getColorRelleno() == Color.PINK)
            parent.getBoxColores2().setSelectedItem(Color.PINK);
        
        else if(lienzo.getColorRelleno() == Color.ORANGE)
            parent.getBoxColores2().setSelectedItem(Color.ORANGE);
         
        else if(lienzo.getColorRelleno() == Color.GRAY)
            parent.getBoxColores2().setSelectedItem(Color.GRAY);
        */
        parent.getBoxColores().setSelectedItem(lienzo.getColorAsignado());
        parent.getBoxColores2().setSelectedItem(lienzo.getColorRelleno());
        parent.getFuentes().setSelectedItem(lienzo.getTipoFuente());
        repaint();
        
        
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private SM.AVC.IU.LienzoProyecto lienzo;
    // End of variables declaration//GEN-END:variables
}
